version: '{build}-{branch}'
install:
  - bundle config path vendor/bundle
  - bundle install -j4
build: off
test_script:
  - ps: |
      $path = $env:Path
      $rubypaths = ls -Path C:\Ruby*\bin
      $ErrorActionPreference = "Stop"
      foreach ($rubypath in $rubypaths) {
        echo "################################################################################"
        $env:Path = "$rubypath;" + $path
        ruby --version
        bundle exec rspec
        if ($LASTEXITCODE -gt 0) {
          exit 1
        }
      }
      $env:Path = $path
