name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 6
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '1.9'
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
        - jruby-9.3
        - jruby-9.4
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - run: bundle exec rspec
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby:
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - run: bundle exec rspec
